"""Phase 6 final validation (brief §55): 8 scenarios run through the implementation, with the session state
transitions, query ledger, evidence lifecycle, claim lifecycle and answer versions written out for manual inspection.

Fixture corpus (fictional) with the bge-small stack: behaviour demonstration only, NOT a benchmark result.
Output: research/phase6/results/final_validation.md (generated; nothing hand-written).

Usage: .venv/bin/python research/phase6/final_validation.py --index-root /tmp/idx6
"""

from __future__ import annotations

import argparse
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
OUT = Path(__file__).resolve().parent / "results" / "final_validation.md"

from streamrag.config import load_config  # noqa: E402
from streamrag.retrieval import build_index  # noqa: E402
from streamrag.session import AdaptivePipeline  # noqa: E402
from streamrag.streaming.factory import build_stack  # noqa: E402

LADDERS = "What are the rules for ladders in the orchard?"
SCENARIOS = [
    ("1 new constraint", [LADDERS, "Specifically overnight."]),
    ("2 new intent", [LADDERS, "And how is the lens cleaned?"]),
    ("3 entity correction", [LADDERS, "Sorry, I meant crates instead of ladders."]),
    ("4 constraint removal", ["What are the rules for ladders in the orchard, especially overnight?",
                              "Ignore the overnight restriction."]),
    ("5 follow-up", [LADDERS, "What about crates?"]),
    ("6 unchanged continuation", [LADDERS, "Okay.", "Thanks."]),
    ("7 evidence reuse", [LADDERS, "Specifically overnight.", "Never mind the overnight restriction."]),
    ("8 evidence invalidation", ["How are crates handled at harvest?", "Only for the night shift."]),
]


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--index-root", type=Path, required=True)
    a = ap.parse_args()
    cfg = load_config(REPO / "configs" / "default.yaml",
                      {"paths.corpus": str(REPO / "tests/fixtures/corpus"), "paths.index_root": str(a.index_root),
                       "telemetry.log_level": "ERROR", "multi_intent.enabled": True, "session.enabled": True},
                      base_dir=REPO)
    stack = build_stack(cfg, build_index(cfg).path)
    L = ["# Phase 6 final validation (generated)", "",
         "> TEST FIXTURE corpus (fictional), bge-small stack - behaviour demonstration only, NOT a benchmark result. "
         "Generated by `research/phase6/final_validation.py`.", ""]
    for name, turns in SCENARIOS:
        p = AdaptivePipeline(stack, session_id=name.split()[0])
        L += [f"## Scenario {name}", ""]
        for n, text in enumerate(turns, start=1):
            r = p.process(f"u{n}", text, n * 3000.0)
            L.append(f"**u{n}** \"{text}\": gate `{r.gate}`, changes "
                     f"{[(c.change_type, c.affected_intents, c.new_intents, c.added_constraints, c.removed_constraints) for c in r.changes]}, "
                     f"retrievals {r.retrievals}, cache hits {r.cache_hits}, reused active {r.reused_active}")
            if r.plan:
                L.append(f"  - plan {r.plan.plan_id}: create {[(x.intent_id, x.query.text) for x in r.plan.queries_to_create]}"
                         f", reuse {[(x.intent_id, x.action, x.reused_query_id) for x in r.plan.queries_to_reuse]}"
                         f", supersede {r.plan.queries_to_supersede}, claims to revalidate {r.plan.claims_to_revalidate}")
            if r.answer:
                d = r.answer.diff
                L.append(f"  - answer {r.answer.answer_id} ({r.answer.kind}, frame {r.answer.topic_id}): kept {d.kept}, "
                         f"modified {[(m.claim_id, m.from_status, m.to_status) for m in d.modified]}, added {d.added}, "
                         f"retracted {d.retracted}, re-render {[s.section_id for s in r.answer.sections if s.needs_regeneration]}"
                         f", uncertainty {[u.kind for u in r.answer.uncertainty]}")
        e = p.engine
        L += ["", "Session versions:", ""]
        L += [f"- v{v.version_id} (parent {v.parent_version}, {v.trigger}, {v.utterance_id}): {v.summary}" for v in e.memory.versions]
        L += ["", "Query ledger:", ""]
        for q in e.ledger.all():
            L.append(f"- {q.query_id} [{q.intent_id} v{q.intent_version}] {q.status}{' stale' if q.stale else ''} "
                     f"\"{q.query_text}\" parent={q.parent_query_id} change={q.derived_from_change_id} "
                     f"reused_from={q.reused_from} evidence={len(q.evidence_ids)}")
        L += ["", "Evidence lifecycle (assignment: transitions):", ""]
        for (eid, iid), asg in e.store.assign.items():
            L.append(f"- {eid}@{iid}: " + " -> ".join(f"{t.to_status}({t.rule})" for t in asg.history))
        L += ["", "Claim lifecycle:", ""]
        for cid, c in e.graph.claims.items():
            hist = [t for t in e.graph.transitions if t.claim_id == cid]
            L.append(f"- {cid} [{c.intent_id}] \"{c.text[:80]}\": " + " -> ".join(f"{t.to_status}({t.reason.split(':')[0]})" for t in hist))
        L += ["", "Final state:", "", f"- frames {[(f.frame_id, f.status, f.intent_ids) for f in e.frames.frames]}",
              f"- constraints {[(k.constraint_id, k.text, k.status, k.applies_to) for k in e.tracker.constraints.values()]}",
              f"- evidence {e.store.counts()}, claims {e.graph.status_counts()}", ""]
        p.close()
    OUT.write_text("\n".join(L) + "\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
