"""SYNTHETIC text for latency/throughput measurement ONLY (not corpus content, never used for quality claims).

Words are sampled (Zipf-weighted, seeded) from the vocabulary of the fictional test fixtures so that the
tokenizer sees English-like words (realistic wordpiece counts). Generated corpora carry the TEST_FIXTURE_ONLY
marker, so every index/benchmark built from them is labeled as a fixture.
"""

from __future__ import annotations

import re
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parents[2]
FIX = REPO / "tests" / "fixtures" / "corpus"
MARKER = "TEST FIXTURE ONLY - synthetic latency corpus generated by research/phase3/synth.py. Not a real corpus.\n"


def vocabulary() -> list[str]:
    words: list[str] = []
    for p in sorted(FIX.glob("*")):
        if p.suffix in (".md", ".txt"):
            words += re.findall(r"[a-z]+", p.read_text().lower())
    uniq = sorted(set(words), key=lambda w: (-words.count(w), w))
    return uniq


def _sampler(seed: int):
    vocab = vocabulary()
    rng = np.random.default_rng(seed)
    p = 1.0 / np.arange(1, len(vocab) + 1)
    p /= p.sum()
    return vocab, rng, p


def sentence(vocab, rng, p, n_words: int) -> str:
    w = list(rng.choice(vocab, size=n_words, p=p))
    return " ".join(w).capitalize() + "."


def passages(n: int, words: int = 180, seed: int = 0) -> list[str]:
    vocab, rng, p = _sampler(seed)
    out = []
    for _ in range(n):
        sents, total = [], 0
        while total < words:
            k = int(rng.integers(8, 20))
            sents.append(sentence(vocab, rng, p, k))
            total += k
        out.append(" ".join(sents))
    return out


def queries(n: int, seed: int = 1) -> list[str]:
    vocab, rng, p = _sampler(seed)
    return [" ".join(rng.choice(vocab, size=int(rng.integers(4, 9)), p=p)) for _ in range(n)]


def make_corpus(target: Path, n_docs: int, sections: int = 8, paras: int = 3, seed: int = 0) -> Path:
    """Write ``n_docs`` .txt files with numbered sections of ``paras`` ~60-word paragraphs."""
    vocab, rng, p = _sampler(seed)
    target.mkdir(parents=True, exist_ok=True)
    (target / "TEST_FIXTURE_ONLY").write_text(MARKER)
    for d in range(n_docs):
        lines = [f"SYNTHETIC LATENCY DOCUMENT {d}", MARKER.strip(), ""]
        for s in range(1, sections + 1):
            lines += [f"{s}. " + " ".join(rng.choice(vocab, size=3, p=p)).title(), ""]
            for _ in range(paras):
                lines += [" ".join(sentence(vocab, rng, p, int(rng.integers(8, 18))) for _ in range(5)), ""]
        (target / f"synthetic_{d:05d}.txt").write_text("\n".join(lines))
    return target
