"""Brief §66 quality test with the REAL local LLM (Ollama qwen3:4b): grounded answer quality of fixed hybrid vs the
adaptive policy (H1 quality side), and of adaptive-k without vs with claim-driven requirements (H2).

Same harness as run_benchmarks.py, but the answer is generated by the local model and verified by the Phase 7
verifier (NLI + rules): claim support = raw claims supported / raw claims (before the unsupported-claim policy),
unsupported = raw claims without support, citation precision, gold cited = share of gold sections cited by the final
answer. One run per case (temperature 0, seed 7). NOT REPORTABLE (fixture corpora, implementer labels).

Usage: .venv/bin/python research/phase9/llm_quality.py --index-root /tmp/idx9    (needs `ollama serve`)
"""

from __future__ import annotations

import argparse
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import ABLATIONS, SYSTEMS, cases, mean, meta, pct, run_case, stack, write  # noqa: E402

from streamrag.generation.llm import OllamaBackend  # noqa: E402

PAIRS = {"C_fixed_hybrid": SYSTEMS["C_fixed_hybrid"], "ADAPTIVE": SYSTEMS["ADAPTIVE"],
         "AB_C_adaptive_k": ABLATIONS["AB_C_adaptive_k"], "AB_D_claim_driven": ABLATIONS["AB_D_claim_driven"]}


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--index-root", type=Path, required=True)
    ap.add_argument("--model", default="qwen3:4b")
    a = ap.parse_args()
    url = "http://127.0.0.1:11434"
    if not OllamaBackend.reachable(url, a.model):
        raise SystemExit("needs `ollama serve` with the model")
    llm = OllamaBackend(url, a.model)
    llm.complete([{"role": "user", "content": "Reply with {}"}], {"type": "object"})        # load the model
    out = {}
    for name, ov in PAIRS.items():
        if not OllamaBackend.reachable(url, a.model):          # never report extractive fallbacks as LLM results
            raise SystemExit(f"ollama became unreachable before {name}")
        rows = []
        t0 = time.perf_counter()
        for c in cases():
            rows += run_case(stack(c["corpus"], a.index_root, llm=llm), c, {**ov, "generation.backend": "ollama"})
        g = [r for r in rows if r["gold"]]
        out[name] = {"claim_support": mean(r.get("claim_support") for r in rows),
                     "unsupported_rate": mean(r.get("unsupported") for r in rows),
                     "citation_precision": mean(r.get("citation_precision") for r in rows),
                     "gold_cited": mean(r.get("gold_cited") for r in g),
                     "coverage": mean(r["coverage"] for r in g), "mrr@10": mean(r["mrr@10"] for r in g),
                     "insufficient_reported": mean(1.0 if r.get("reports_gap") else 0.0 for r in rows
                                                   if r["expect"] == "INSUFFICIENT"),
                     "conflict_reported": mean(1.0 if r.get("reports_conflict") else 0.0 for r in rows
                                               if r["expect"] == "CONTRADICTORY"),
                     "llm_calls": sum(r.get("llm_calls") or 0 for r in rows),
                     "fallback_turns": sum(1 for r in rows if r.get("fallback")),
                     "searches": sum(r["ops"]["searches"] for r in rows),
                     "turn_latency_ms": pct(r["turn_ms"] for r in rows), "wall_s": round(time.perf_counter() - t0, 1),
                     "rows": rows}
        print(name, {k: v for k, v in out[name].items() if k != "rows"}, flush=True)
    write("llm_quality.json", {"meta": meta(llm=f"{a.model} via local Ollama (REAL model)", generation="ollama",
                                            runs="one run per case"), "systems": out})


if __name__ == "__main__":
    main()
