"""Renders research/phase9/results/*.json into markdown tables (results/tables.md) for the Phase 9 report.

Every number in the report's measurement sections comes from this file's output (no hand transcription).
Usage: .venv/bin/python research/phase9/make_tables.py
"""

from __future__ import annotations

import json
from pathlib import Path

R = Path(__file__).resolve().parent / "results"


def load(name):
    p = R / name
    return json.loads(p.read_text()) if p.exists() else None


def f(x, d=3):
    if x is None:
        return "–"
    if isinstance(x, float):
        return f"{x:.{d}f}"
    return str(x)


def table(head, rows):
    out = ["| " + " | ".join(head) + " |", "|" + "|".join("---" for _ in head) + "|"]
    out += ["| " + " | ".join(f(c) for c in r) + " |" for r in rows]
    return "\n".join(out)


def quality_rows(systems, key="overall"):
    rows = []
    for n, v in systems.items():
        o = v[key] if key in v else v
        rows.append([n, o["recall@5"], o["recall@10"], o["coverage"], o["precision@5"], o["returned_precision"],
                     o["mrr@10"], o["ndcg@10"], o["gold_cited"], o["claim_support"], o["unsupported_rate"],
                     o["citation_precision"]])
    return rows


QH = ["system", "R@5", "R@10", "coverage", "P@5", "returned prec.", "MRR@10", "nDCG@10", "gold cited", "claim support",
      "unsupported", "citation prec."]


def eff_rows(systems, key="overall"):
    rows = []
    for n, v in systems.items():
        o = v[key] if key in v else v
        lat = o["retrieval_latency_ms"]
        rows.append([n, o["searches_total"], o["searches_per_turn"], o["lexical_searches_total"], o["embeddings_total"],
                     o["reranker_calls_total"], o["chunks_retrieved_total"], o["avg_k"], o["cache_hits"],
                     o["phase6_cache_hits"], o["llm_calls"], lat["p50"], lat["p95"], o["retrieval_cpu_ms"]["mean"]])
    return rows


EH = ["system", "searches", "searches/turn", "BM25 searches", "embeddings", "reranker calls", "chunks retrieved", "avg k",
      "adaptive cache / session reuse", "Phase 6 cache hits", "LLM calls", "retr. p50 ms (1 run)", "retr. p95 ms (1 run)",
      "retr. CPU mean ms"]


def main() -> None:
    md = ["# Phase 9 result tables (generated by research/phase9/make_tables.py)", "",
          "> Fixture corpora, implementer-labelled dev set (eval/dev_adaptive_retrieval) - NOT REPORTABLE.", ""]
    b = load("baselines.json")
    if b:
        s = b["systems"]
        md += ["## Baselines vs adaptive - quality (72 turns, 68 with gold)", "", table(QH, quality_rows(s)), "",
               "## Baselines vs adaptive - efficiency", "", table(EH, eff_rows(s)), ""]
        cats = sorted({c for v in s.values() for c in v["by_category"]})
        md += ["## Coverage / MRR by category (C_fixed_hybrid vs ADAPTIVE)", "",
               table(["category", "turns", "cov C", "cov ADAPTIVE", "MRR C", "MRR ADAPTIVE", "searches C",
                      "searches ADAPTIVE"],
                     [[c, s["ADAPTIVE"]["by_category"][c]["turns"], s["C_fixed_hybrid"]["by_category"][c]["coverage"],
                       s["ADAPTIVE"]["by_category"][c]["coverage"], s["C_fixed_hybrid"]["by_category"][c]["mrr@10"],
                       s["ADAPTIVE"]["by_category"][c]["mrr@10"], s["C_fixed_hybrid"]["by_category"][c]["searches_total"],
                       s["ADAPTIVE"]["by_category"][c]["searches_total"]] for c in cats]), ""]
        a = s["ADAPTIVE"]["rows"]
        strat, stops, assess, cx = {}, {}, {}, {}
        for r in a:
            for x in r["strategies"]:
                strat[x] = strat.get(x, 0) + 1
            for x in r["stops"]:
                stops[x] = stops.get(x, 0) + 1
            for x in r["assessments"]:
                assess[x] = assess.get(x, 0) + 1
            for x in r["complexity"]:
                cx[x] = cx.get(x, 0) + 1
        md += ["## ADAPTIVE routing decisions (per need)", "",
               table(["strategy", "needs"], sorted(strat.items(), key=lambda x: -x[1])), "",
               table(["complexity", "needs"], sorted(cx.items(), key=lambda x: -x[1])), "",
               table(["stop reason", "needs"], sorted(stops.items(), key=lambda x: -x[1])), "",
               table(["final evidence state", "needs"], sorted(assess.items(), key=lambda x: -x[1])), ""]
        exp = [r for r in a if r["assessments"]]
        ok = sum(1 for r in exp if r["expect"] in r["assessments"]
                 or (r["expect"] == "SUFFICIENT" and all(x == "SUFFICIENT" for x in r["assessments"])))
        md += [f"Evidence-state agreement with the label (turns with an adaptive run): {ok} / {len(exp)}", ""]
        sess = {n: v["sessions"] for n, v in s.items()}
        md += ["## Sessions only (S-cases, 19 turns)", "", table(EH, eff_rows(sess, key="x")), ""]
    ab = load("ablations.json")
    if ab:
        md += ["## Cumulative ablations A-G - quality", "", table(QH, quality_rows(ab["systems"])), "",
               "## Cumulative ablations A-G - efficiency", "", table(EH, eff_rows(ab["systems"])), "",
               "## Cumulative ablations - sessions only", "",
               table(EH, eff_rows({n: v["sessions"] for n, v in ab["systems"].items()}, key="x")), ""]
    loo = load("ablations_loo.json")
    if loo:
        md += ["## Leave-one-out from the full system - quality", "", table(QH, quality_rows(loo["systems"])), "",
               "## Leave-one-out - efficiency", "", table(EH, eff_rows(loo["systems"])), ""]
    lat = load("latency.json")
    if lat:
        rows = []
        for n in ("C_fixed_hybrid", "ADAPTIVE"):
            L = lat[n]
            rows.append([n, L["retrieval_latency_ms"]["p50"], L["retrieval_latency_ms"]["p95"],
                         L["retrieval_latency_ms"]["mean"], L["retrieval_cpu_ms"]["p50"], L["retrieval_cpu_ms"]["p95"],
                         L["retrieval_cpu_ms"]["mean"], L["turns"], L["reps"]])
        md += ["## Latency test (retrieval stage, 5 interleaved repetitions, per-turn median)", "",
               table(["system", "p50 ms", "p95 ms", "mean ms", "CPU p50 ms", "CPU p95 ms", "CPU mean ms", "turns",
                      "reps"], rows), "",
               "ratio adaptive / fixed: " + json.dumps(lat["ratio_adaptive_over_fixed"]), "",
               table(["category", "p50 C ms", "p50 ADAPTIVE ms"],
                     [[c, lat["C_fixed_hybrid"]["by_category_p50"].get(c), v]
                      for c, v in lat["ADAPTIVE"]["by_category_p50"].items()]), ""]
    cv = load("curves.json")
    if cv:
        md += ["## Quality-efficiency points (retrieval only, one run)", "",
               table(["config", "R@10", "coverage", "MRR@10", "nDCG@10", "returned prec.", "searches/turn",
                      "embeddings", "chunks", "avg k", "latency mean ms", "latency p50 ms"],
                     [[n, p["recall@10"], p["coverage"], p["mrr@10"], p["ndcg@10"], p["returned_precision"],
                       p["searches_per_turn"], p["embeddings_total"], p["chunks_retrieved_total"], p["avg_k"],
                       p["latency_mean_ms"], p["latency_p50_ms"]] for n, p in cv["points"].items()]), ""]
    cal = load("calibration.json")
    if cal:
        sp = cal["simple_path"]
        md += ["## Calibration (eval/dev_grounded + fixture_retrieval; SIMPLE needs)", "",
               table(["strategy", "n", "R@5", "MRR@10", "nDCG@10", "latency mean ms", "embeddings"],
                     [[k, v["simple_only"]["n"], v["simple_only"]["recall@5"], v["simple_only"]["mrr@10"],
                       v["simple_only"]["ndcg@10"], v["simple_only"]["latency_ms"]["mean"],
                       v["simple_only"]["embeddings"]] for k, v in sp.items()]), "",
               "rerank (all calibration items): " + json.dumps({m: {k: cal["rerank"][m]["all"][k] for k in
                                                                   ("recall@5", "mrr@10", "ndcg@10")} |
                                                               {"latency_mean_ms": cal["rerank"][m]["all"]["latency_ms"]["mean"]}
                                                               for m in cal["rerank"]}), "",
               "decision: " + json.dumps(cal["decision"]), ""]
    h5 = load("runtime_h5.json")
    if h5:
        for cond, cfgs in h5["conditions"].items():
            md += [f"## H5 runtime ({cond})", "",
                   table(["config", "wasted ms", "useful ms", "wasted share", "retrieval tasks", "wasted tasks",
                          "cancelled tasks", "queries", "stale discarded", "coverage", "turns completed"],
                         [[n, v["wasted_ms_total"], v["useful_ms_total"], v["wasted_share"], v["retrieval_tasks"],
                           v["wasted_tasks"], v["cancelled_tasks"], v["queries"], v["stale_discarded"], v["coverage"],
                           f"{v['turns_completed']}/{v['turns']}"] for n, v in cfgs.items()]), ""]
    lq = load("llm_quality.json")
    if lq:
        md += ["## Real-LLM grounded quality (qwen3:4b)", "",
               table(["system", "claim support", "unsupported", "citation prec.", "gold cited", "coverage", "MRR@10",
                      "insufficient reported", "conflict reported", "LLM calls", "searches", "turn p50 ms",
                      "turn p95 ms"],
                     [[n, v["claim_support"], v["unsupported_rate"], v["citation_precision"], v["gold_cited"],
                       v["coverage"], v["mrr@10"], v["insufficient_reported"], v["conflict_reported"], v["llm_calls"],
                       v["searches"], v["turn_latency_ms"]["p50"], v["turn_latency_ms"]["p95"]]
                      for n, v in lq["systems"].items()]), ""]
    (R / "tables.md").write_text("\n".join(md) + "\n")
    print("\n".join(md))


if __name__ == "__main__":
    main()
